# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-harmonising',
                'doc_host': 'https://matt-humphrey.github.io',
                'git_url': 'https://github.com/matt-humphrey/data-harmonising',
                'lib_path': 'data_harmonising'},
  'syms': {'data_harmonising.core': {'data_harmonising.core.foo': ('core.html#foo', 'data_harmonising/core.py')}}}
