# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_test.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_test.ipynb 2
from .data import *
from fastcore.utils import *

# %% ../nbs/00_test.ipynb 3
import pandas as pd
import dask.dataframe as dd
import pyreadstat
import pyspssio
